### ISSUE TITLE
Launcherdefaults not needed

### ISSUE THREAD

**Issue by ribab** [pmix/pmix-tests#14]
@rhc54  I was checking out your INI files and found a piece of it that isn't needed. You can take out these lines since you aren't using the SLURM plugin in this INI file. 👍 

https://github.com/pmix/pmix-tests/blob/130df0976026a243b5e9bbadec6ce5deedf29499/intel/pmix_python.ini#L74-L81

**Comment by rhc54** [comment]
Yeah, I had already removed it locally - but thanks for pointing it out!
